using UnityEngine;
using UnityEngine.AI;
using UnityEngine.InputSystem;
using UnityEngine.SceneManagement;

public class Player : MonoBehaviour
{
    [Header("кё°ліё м„Өм •")] public float moveSpeed = 5f;

    [Header("мқёлІӨнҶ лҰ¬ м„Өм •")] private bool isOpenInventory = false;
    [SerializeField] public InventoryUIManager inventoryUIManager; // м—°кІ°н•  мқёлІӨнҶ лҰ¬ UI кҙҖлҰ¬мһҗ

    [Header("мғҒнҳёмһ‘мҡ© м„Өм •")][SerializeField] private float InteractionRange = 1f;
    [SerializeField] private LayerMask interactableLayer; // мғҒнҳёмһ‘мҡ©н•  м•„мқҙн…ң л Ҳмқҙм–ҙ
    [SerializeField] private Transform interactionPoint; // мғҒнҳёмһ‘мҡ© м§Җм җ

    private Vector2 _moveInput;
    private bool _isSprint;
    private readonly float _runRate = 1.8f; // кұ·лҠ” мҶҚл Ҙкіј л№„көҗн•ң лӢ¬лҰ¬кё° мҶҚл Ҙл№„
    private Rigidbody2D _rb;
    private Animator _animator;
    private SpriteRenderer _sr;
    private Collider2D _col;

    private void Awake()
    {
        _rb = GetComponent<Rigidbody2D>();
        _animator = GetComponent<Animator>();
        _sr = GetComponentInChildren<SpriteRenderer>();
        _col = GetComponent<Collider2D>();
    }

    void OnEnable()
    {
        SceneManager.sceneLoaded += OnSceneLoaded;
    }

    void OnDisable()
    {
        SceneManager.sceneLoaded -= OnSceneLoaded;
    }

    private void OnSceneLoaded(Scene scene, LoadSceneMode mode)
    {
        bool disable = scene.name == "bench" || scene.name == "distiller" || scene.name == "Mixture";

        SetPlayerDisenabled(disable);
    }

    void SetPlayerDisenabled(bool disabled)
    {
        if (_rb)
        {
            _rb.linearVelocity = Vector2.zero;
            _rb.simulated = !disabled;
        }
        if (_animator) _animator.enabled = !disabled;
        if (_sr) _sr.enabled = !disabled;
        if (_col) _col.enabled = !disabled;
    }

    private void Update()
    {
        if (PauseManager.Instance.IsPlayerMovementBlocked() || isOpenInventory)
        {
            if (_moveInput != Vector2.zero)
            {
                _moveInput = Vector2.zero;
            }
            return;
        }

    }

    void FixedUpdate()
    {
        // мқёлІӨнҶ лҰ¬ м—¬л©ҙ лӘ» мӣҖм§ҒмқҙкІҢ
        if (PauseManager.Instance.IsPlayerMovementBlocked() || isOpenInventory)
        {
            _rb.linearVelocity = Vector2.zero;
            _animator.SetBool("isWalking", false);
            return;
        }

        // мһ…л Ҙмқҙ кұ°мқҳ м—Ҷмңјл©ҙ л©Ҳм¶”кі  Idle мң м§Җ
        if (_moveInput.magnitude <= 0.01f)
        {
            _rb.linearVelocity = Vector2.zero;
            _animator.SetBool("isWalking", false);
            return;
        }

        // мӣҖм§Ғмқј л•Ңл§Ң мҶҚлҸ„ м Ғмҡ©
        Vector2 movement = _isSprint ? _moveInput * (moveSpeed * _runRate) : _moveInput * moveSpeed;
        _rb.linearVelocity = movement;
    }

    void OnMove(InputValue value)
    {
        if (PauseManager.Instance.IsPlayerMovementBlocked() || isOpenInventory) return;
        _moveInput = value.Get<Vector2>();
        UpdateAnimator(_moveInput);
    }

    private void UpdateAnimator(Vector2 input)
    {
        float magnitude = input.magnitude;

        if (magnitude <= 0.01f)
        {
            // Idle мғҒнғңм—җм„ңлҠ” isWalkingл§Ң false, л°©н–Ҙ к°’мқҖ к·ёлҢҖлЎң мң м§Җ
            _animator.SetBool("isWalking", false);
            return;
        }

        // мӣҖм§ҒмқҙлҠ” кІҪмҡ°м—җл§Ң нҢҢлқјлҜён„° к°ұмӢ 
        _animator.SetBool("isWalking", true);
        _animator.SetFloat("InputX", input.x);
        _animator.SetFloat("InputY", input.y);
        SetLastInputDirection(input);  // л§Ҳм§Җл§ү л°©н–Ҙ к°ұмӢ 
    }

    //
    private void SetLastInputDirection(Vector2 input)
    {
        _animator.SetFloat("LastInputX", input.x);
        _animator.SetFloat("LastInputY", input.y);
    }


    void OnSprint(InputValue value)
    {
        _isSprint = value.Get<float>() > 0.5f;
        Debug.Log("Sprint state: " + _isSprint);
    }

    // мқёлІӨнҶ лҰ¬ м—ҙкё°
    void OnOpenInventory(InputValue value)
    {
        isOpenInventory = !isOpenInventory;

        if (inventoryUIManager != null)
        {
            inventoryUIManager.ToggleFullInventory();
        }
        else
        {
            Debug.LogWarning("InventoryUIManagerк°Җ Player мҠӨнҒ¬лҰҪнҠём—җ м—°кІ°лҗҳм§Җ м•Ҡм•ҳмҠөлӢҲлӢӨ.");
        }
    }

    // м•„мқҙн…ң/NPC л“ұ мғҒнҳёмһ‘мҡ©
    // PlayerInputмңјлЎң мһ…л Ҙ л°ӣмқ„ мҲҳ мһҲлҸ„лЎқ мҲҳм •мӨ‘ >> кё°нҡҚм„ңм—җ л§һм¶°м„ң нӮӨліҙл“ң/л§Ҳмҡ°мҠӨ мғҒнҳёмһ‘мҡ©мңјлЎң лӮҳлҲ”
    void OnInteract(InputValue value)
    {
        if (Mouse.current != null && Mouse.current.leftButton.wasPressedThisFrame)
        {
            MouseInteration();
        }
        else if (Keyboard.current != null && Keyboard.current.spaceKey.wasPressedThisFrame)
        {
            KeyboardInteration();
        }
    }

    // л§Ҳмҡ°мҠӨлЎң мғҒнҳёмһ‘мҡ©
    private void MouseInteration()
    {
        // л§Ҳмҡ°мҠӨ мң„м№ҳ к°җм§Җ + мҳӨлёҢм қнҠё к°җм§Җ
        Vector2 mousePos = Camera.main.ScreenToWorldPoint(Mouse.current.position.ReadValue());
        RaycastHit2D detection = Physics2D.Raycast(mousePos, Vector2.zero, 0f, interactableLayer);

        if (detection.collider != null)
        {
            // мҡ°м„ мҲңмң„ лі„лЎң мғҒнҳёмһ‘мҡ© мҳӨлёҢм қнҠё мғҒнҳёмһ‘мҡ© (мһ‘л¬ј > лҶҚм§Җ > л°”лӢҘм—җ мһҲлҠ” м•„мқҙн…ң)
            // н”Ңл Ҳмқҙм–ҙ мң„м№ҳмҷҖ к°җм§Җлҗң мҳӨлёҢм қнҠё мӮ¬мқҙмқҳ кұ°лҰ¬ кі„мӮ°
            float distaceToTarget = Vector2.Distance(transform.position, detection.collider.transform.position);
            if (distaceToTarget > InteractionRange)
            {
                return;
            }

            IInteract interact = detection.collider.GetComponent<IInteract>();
            if (interact != null) interact.Interact(this);
        }

        Debug.Log($"мғҒнҳёмһ‘мҡ© м—ҶмқҢ");
    }

    //нӮӨліҙл“ңлЎң мғҒнҳёмһ‘мҡ©
    private void KeyboardInteration()
    {
        Vector2 origin = interactionPoint != null ? interactionPoint.position : transform.position;

        // мЈјліҖ мғҒнҳёмһ‘мҡ© к°ҖлҠҘ мҳӨлёҢм қнҠё мЎҙмһ¬ м—¬л¶Җ нҢҗлӢЁ
        Collider2D[] hitColliders = Physics2D.OverlapCircleAll(origin, InteractionRange, interactableLayer);

        // лӘЁл“  мҪңлқјмқҙлҚ” нҷ•мқё
        foreach (Collider2D hitCollider in hitColliders)
        {
            // кұ°лҰ¬к°Җ л„Ҳл¬ҙ лЁј кІҪмҡ°
            if (Vector2.Distance(transform.position, hitCollider.transform.position) > InteractionRange)
            {
                continue;
            }
            // мҡ°м„ мҲңмң„ лі„лЎң мғҒнҳёмһ‘мҡ© мҳӨлёҢм қнҠё мғҒнҳёмһ‘мҡ© (мһ‘л¬ј > лҶҚм§Җ > л°”лӢҘм—җ мһҲлҠ” м•„мқҙн…ң)

            // мҳ¬л°”лҘё лҸ„кө¬лҘј мһҘм°©н–ҲлҠ”м§Җ нҷ•мқё >> лҸ„кө¬к°Җ л¬ҙмҠЁ мў…лҘҳмқём§Җ нҷ•мқё н•„мҡ”

            IInteract interact = hitCollider.GetComponent<IInteract>();
            interact.Interact(this);

            return;
        }

        Debug.Log($"мғҒнҳёмһ‘мҡ© м—ҶмқҢ");
    }

    // PlayerInputм—җм„ң Pause м•Ўм…ҳ нҳём¶ң мӢң м—°кІ°
    public void OnPause(InputValue value)
    {
        PauseManager.Instance.TogglePause(true);
    }
}